name = "Bertini"
uuid = "e878e6a3-2037-4ac5-b347-3944c480de5d"
authors = ["Sascha Timme <sascha@timme.xyz>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
